# Generated by Django 5.1.7 on 2025-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_profile"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(
                related_name="profiles",
                through="skills.UserSkill",
                to="skills.skillcategory",
            ),
        ),
    ]
