# Generated by Django 5.1.7 on 2025-04-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_profile_skills"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_skills",
                to="auth_app.profile",
            ),
        ),
    ]
